/**
 * Home — Main subtitle extraction tool page.
 * Extracted from App.tsx into a proper page component.
 */

import { useState, useCallback, useRef, useEffect, memo } from 'react';
import {
  Download, Search, AlertCircle, Zap, Shield, Globe2,
  CheckCircle2, ChevronDown, Clock, Trash2, ExternalLink,
  FileText, Captions, Sparkles, Play, RefreshCw,
} from 'lucide-react';
import Layout from '../components/Layout';
import { usePageMeta } from '../hooks/usePageMeta';

// ── Types ────────────────────────────────────────────────────────────────────
interface Subtitle {
  language: string;
  languageCode: string;
  url: string;
  format: string;
  isAutoGenerated?: boolean;
  name?: string;
}

interface ExtractResponse {
  platform: string;
  title: string;
  thumbnail?: string;
  subtitles: Subtitle[];
  error?: string;
}

interface RecentSearch {
  url: string;
  title: string;
  platform: string;
  timestamp: number;
}

type DownloadFormat = 'srt' | 'vtt' | 'txt';

// ── Config ───────────────────────────────────────────────────────────────────
const PLATFORMS: Record<string, { badge: string; icon: string; color: string }> = {
  YouTube:     { badge: 'badge-youtube', icon: '▶', color: 'var(--yt)'    },
  Vimeo:       { badge: 'badge-vimeo',   icon: '◈', color: 'var(--vimeo)' },
  Dailymotion: { badge: 'badge-dm',      icon: '◉', color: 'var(--dm)'    },
};

const FORMATS: Record<DownloadFormat, { label: string; title: string }> = {
  srt: { label: 'SRT', title: 'SubRip — for video editors & media players' },
  vtt: { label: 'VTT', title: 'WebVTT — for web players & browsers'        },
  txt: { label: 'TXT', title: 'Plain text — for reading, AI & research'     },
};

const FAQS = [
  {
    q: 'Which video platforms are supported?',
    a: 'SubFetch supports YouTube (including auto-generated captions), Vimeo, and Dailymotion. More platforms are on the roadmap.',
  },
  {
    q: 'What subtitle formats can I download?',
    a: 'You can download in SRT (for video editors and most media players), VTT (for web players), or TXT (plain text — great for AI summarization, translation, or research).',
  },
  {
    q: 'Are auto-generated captions supported?',
    a: 'Yes! YouTube auto-generated (ASR) captions are listed with an "Auto" badge so you can tell them apart from manually added subtitles.',
  },
  {
    q: 'Is it free and safe to use?',
    a: "Completely free — no sign-up, no watermarks, no limits. Your URLs are never stored. The Worker is stateless and runs on Cloudflare's global edge network.",
  },
  {
    q: "Why doesn't a video have subtitles?",
    a: 'Captions must be enabled by the video uploader. Private, age-restricted, or live videos often have no subtitles available.',
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────
function detectPlatform(url: string): string | null {
  if (/youtube\.com|youtu\.be/.test(url)) return 'YouTube';
  if (/vimeo\.com/.test(url)) return 'Vimeo';
  if (/dailymotion\.com|dai\.ly/.test(url)) return 'Dailymotion';
  return null;
}

function loadRecent(): RecentSearch[] {
  try { return JSON.parse(localStorage.getItem('subfetch_v2_recent') || '[]'); }
  catch { return []; }
}

function saveRecent(item: RecentSearch) {
  try {
    const prev = loadRecent().filter(r => r.url !== item.url);
    localStorage.setItem('subfetch_v2_recent', JSON.stringify([item, ...prev].slice(0, 5)));
  } catch {}
}

// ── Sub-components ────────────────────────────────────────────────────────────

function SkeletonCard() {
  return (
    <div className="card p-5 flex gap-4 items-center" aria-hidden="true">
      <div className="skel anim-shimmer w-11 h-11 rounded-lg" />
      <div className="flex-1 space-y-2">
        <div className="skel anim-shimmer h-4 w-28 rounded" />
        <div className="skel anim-shimmer h-3 w-16 rounded" />
      </div>
      <div className="skel anim-shimmer h-9 w-24 rounded-xl" />
    </div>
  );
}

const SubtitleCard = memo(function SubtitleCard({
  sub, title, index,
}: { sub: Subtitle; title: string; index: number }) {
  const [format, setFormat] = useState<DownloadFormat>('srt');
  const [downloading, setDownloading] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = useCallback(() => {
    if (downloading) return;
    setDownloading(true);
    setDone(false);
    const params = new URLSearchParams({ url: sub.url, format, title, lang: sub.languageCode });
    const a = document.createElement('a');
    a.href = `/api/download?${params}`;
    a.download = '';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setDone(true);
    setTimeout(() => { setDownloading(false); setDone(false); }, 2500);
  }, [sub.url, sub.languageCode, format, title, downloading]);

  const code = sub.languageCode.split('-')[0].toUpperCase().slice(0, 3);

  return (
    <article
      className="card p-4 sm:p-5 flex flex-col sm:flex-row items-start sm:items-center gap-4 anim-slide-up"
      style={{ animationDelay: `${Math.min(index * 55, 400)}ms`, opacity: 0 }}
      aria-label={`Subtitle: ${sub.language}`}
    >
      <div className="lang-icon" title={sub.languageCode}>{code}</div>
      <div className="flex-1 min-w-0">
        <div className="flex flex-wrap items-center gap-2 mb-0.5">
          <span className="font-bold text-white text-sm">{sub.language}</span>
          {sub.isAutoGenerated && <span className="badge badge-auto">Auto</span>}
        </div>
        <p className="text-xs" style={{ color: 'var(--text-subtle)', letterSpacing: '0.04em', textTransform: 'uppercase' }}>
          {sub.languageCode}
        </p>
      </div>
      <div className="flex items-center gap-1.5 flex-wrap">
        {(Object.keys(FORMATS) as DownloadFormat[]).map(f => (
          <button key={f} onClick={() => setFormat(f)} className={`pill ${format === f ? 'active' : ''}`}
            title={FORMATS[f].title} aria-pressed={format === f}>{FORMATS[f].label}</button>
        ))}
      </div>
      <button onClick={handleDownload} disabled={downloading}
        className="btn-primary px-5 py-2.5 text-sm shrink-0"
        id={`dl-${sub.languageCode}-${index}`}
        aria-label={`Download ${sub.language} as ${format.toUpperCase()}`}>
        {done ? (
          <><CheckCircle2 className="w-4 h-4" /> Saved!</>
        ) : downloading ? (
          <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full anim-spin" /> Saving…</>
        ) : (
          <><Download className="w-4 h-4" /> Download</>
        )}
      </button>
    </article>
  );
});

function RecentSearches({ searches, onSelect, onClear }: {
  searches: RecentSearch[]; onSelect: (url: string) => void; onClear: () => void;
}) {
  if (!searches.length) return null;
  return (
    <div className="glass rounded-2xl p-4 mt-4 anim-slide-up" style={{ opacity: 0, animationDelay: '100ms' }}>
      <div className="flex items-center justify-between mb-2">
        <span className="eyebrow flex items-center gap-1.5"><Clock className="w-3 h-3" />Recent</span>
        <button onClick={onClear} className="flex items-center gap-1 text-xs font-medium hover:text-red-400 transition-colors"
          style={{ color: 'var(--text-muted)' }} aria-label="Clear recent searches">
          <Trash2 className="w-3 h-3" /> Clear
        </button>
      </div>
      <ul className="space-y-0.5">
        {searches.map((s, i) => {
          const p = PLATFORMS[s.platform];
          return (
            <li key={i}>
              <button onClick={() => onSelect(s.url)}
                className="w-full text-left px-3 py-2 rounded-xl hover:bg-white/5 transition-colors flex items-center gap-3 group"
                aria-label={`Re-search: ${s.title}`}>
                <span className="text-sm" style={{ color: p?.color || 'var(--text-muted)' }}>{p?.icon || '▶'}</span>
                <span className="flex-1 text-sm truncate" style={{ color: 'var(--text)' }}>{s.title}</span>
                <ExternalLink className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" style={{ color: 'var(--text-muted)' }} />
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

function StepCard({ n, title, desc, delay }: { n: string; title: string; desc: string; delay: number }) {
  return (
    <div className="card p-7 relative overflow-hidden anim-slide-up" style={{ opacity: 0, animationDelay: `${delay}ms` }}>
      <div aria-hidden="true" className="absolute top-0 right-4 text-[100px] font-black leading-none select-none"
        style={{ color: 'rgba(255,255,255,0.03)', fontFamily: 'var(--font-head)' }}>{n}</div>
      <div className="btn-primary w-11 h-11 text-lg font-black mb-5 shrink-0" style={{ borderRadius: 'var(--r-md)', padding: 0 }}
        aria-hidden="true">{n}</div>
      <h3 className="font-bold text-white text-base mb-2" style={{ fontFamily: 'var(--font-head)' }}>{title}</h3>
      <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{desc}</p>
    </div>
  );
}

function FAQItem({ q, a, index }: { q: string; a: string; index: number }) {
  return (
    <details className="card overflow-hidden anim-slide-up" style={{ opacity: 0, animationDelay: `${index * 70}ms` }}>
      <summary className="flex items-center justify-between gap-4 p-5 sm:p-6 font-semibold text-white hover:text-[var(--accent)] transition-colors">
        <span className="text-sm sm:text-base">{q}</span>
        <ChevronDown className="chevron w-5 h-5 shrink-0" style={{ color: 'var(--text-muted)' }} />
      </summary>
      <div className="faq-body">
        <div className="px-5 sm:px-6 pb-5">
          <div className="divider mb-4" />
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{a}</p>
        </div>
      </div>
    </details>
  );
}

function FeatureCard({ icon, title, desc, delay }: {
  icon: React.ReactNode; title: string; desc: string; delay: number;
}) {
  return (
    <div className="card p-6 anim-slide-up" style={{ opacity: 0, animationDelay: `${delay}ms` }}>
      <div className="btn-primary w-10 h-10 mb-4 shrink-0" style={{ borderRadius: 'var(--r-sm)', padding: 0 }}
        aria-hidden="true">{icon}</div>
      <h3 className="font-bold text-white text-sm mb-2" style={{ fontFamily: 'var(--font-head)' }}>{title}</h3>
      <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>{desc}</p>
    </div>
  );
}

// ── Page ─────────────────────────────────────────────────────────────────────
export default function Home() {
  usePageMeta({
    title: 'SubFetch — Free Subtitle Downloader for YouTube, Vimeo & Dailymotion',
    description: 'Instantly extract and download subtitles from YouTube, Vimeo, and Dailymotion. Get SRT, VTT, or TXT format free. No sign-up.',
    canonical: 'https://downsub.cybercoderbd.com/',
  });

  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<ExtractResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [platform, setPlatform] = useState<string | null>(null);
  const [recent, setRecent] = useState<RecentSearch[]>(loadRecent);
  const inputRef = useRef<HTMLInputElement>(null);

  // ⌘K / Ctrl+K → focus input
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        inputRef.current?.focus();
        inputRef.current?.select();
      }
    };
    addEventListener('keydown', handler);
    return () => removeEventListener('keydown', handler);
  }, []);

  const onUrlChange = (val: string) => { setUrl(val); setPlatform(detectPlatform(val)); };

  const doExtract = useCallback(async (targetUrl: string) => {
    if (!targetUrl.trim()) return;
    setLoading(true); setError(null); setData(null);
    try {
      const res = await fetch(`/api/extract?url=${encodeURIComponent(targetUrl)}`);
      const json: ExtractResponse = await res.json();
      if (!res.ok) throw new Error(json.error || `Server error ${res.status}`);
      setData(json);
      saveRecent({ url: targetUrl, title: json.title, platform: json.platform, timestamp: Date.now() });
      setRecent(loadRecent());
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : 'An unexpected error occurred.');
    } finally {
      setLoading(false);
    }
  }, []);

  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); doExtract(url); };

  const handleSelectRecent = (u: string) => { setUrl(u); setPlatform(detectPlatform(u)); doExtract(u); };

  const handleReset = () => {
    setData(null); setError(null); setUrl(''); setPlatform(null);
    setTimeout(() => inputRef.current?.focus(), 80);
  };

  const showSections = !data && !loading;

  return (
    <Layout>
      <main id="main-content">

        {/* ── Hero ─────────────────────────────────────────────── */}
        <section
          style={{ maxWidth: '72rem', margin: '0 auto', padding: '5rem 1.5rem 3.5rem' }}
          aria-labelledby="hero-heading"
        >

          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1.25rem' }} className="anim-slide-up delay-0">
            <span className="badge badge-purple">
              <Zap className="w-2.5 h-2.5 fill-current" /> Free · Instant · No sign-up
            </span>
          </div>

          <h1
            id="hero-heading"
            className="anim-slide-up delay-75"
            style={{
              fontFamily: 'var(--font-head)',
              opacity: 0,
              fontSize: 'clamp(2.4rem, 7vw, 5rem)',
              fontWeight: 900,
              color: 'white',
              textAlign: 'center',
              lineHeight: 1.06,
              letterSpacing: '-0.03em',
              marginBottom: '1.25rem',
            }}
          >
            Download{' '}<span className="grad-text">Subtitles</span>
            <br />{' '}in Seconds
          </h1>

          <p
            className="anim-slide-up delay-150"
            style={{
              color: 'var(--text-muted)',
              opacity: 0,
              fontSize: 'clamp(0.95rem, 2vw, 1.1rem)',
              textAlign: 'center',
              maxWidth: '42rem',
              margin: '0 auto 2.5rem',
              lineHeight: 1.7,
            }}
          >
            Extract captions from{' '}
            <strong style={{ color: 'white', fontWeight: 600 }}>YouTube</strong>,{' '}
            <strong style={{ color: 'white', fontWeight: 600 }}>Vimeo</strong>, and{' '}
            <strong style={{ color: 'white', fontWeight: 600 }}>Dailymotion</strong>.{' '}
            Download as SRT, VTT, or TXT — completely free.
          </p>

          {/* Search form */}
          <div
            className="anim-slide-up delay-225"
            style={{ maxWidth: '48rem', margin: '0 auto', opacity: 0 }}
          >
            <form onSubmit={handleSubmit} role="search" aria-label="Subtitle extraction">
              <div
                className="input-wrap"
                style={{ padding: '10px', display: 'flex', flexDirection: 'row', gap: '8px', boxShadow: '0 32px 80px rgba(0,0,0,0.5)', flexWrap: 'wrap' }}
              >
                <div style={{ position: 'relative', flex: 1, minWidth: '200px', display: 'flex', alignItems: 'center' }}>
                  <Search className="absolute left-4 w-5 h-5 pointer-events-none" style={{ color: 'var(--text-muted)' }} aria-hidden="true" />
                  <input
                    ref={inputRef}
                    id="url-input"
                    type="url"
                    name="url"
                    className="input-field pl-12 pr-4 py-3.5"
                    placeholder="Paste YouTube, Vimeo, or Dailymotion URL…"
                    value={url}
                    onChange={e => onUrlChange(e.target.value)}
                    required
                    autoFocus
                    autoComplete="off"
                    spellCheck="false"
                    aria-label="Video URL"
                    aria-describedby="url-hint"
                  />
                  {platform && PLATFORMS[platform] && (
                    <span className={`badge ${PLATFORMS[platform].badge} absolute right-3 anim-fade-in hide-sm`}
                      style={{ opacity: 0 }} aria-live="polite">
                      {PLATFORMS[platform].icon} {platform}
                    </span>
                  )}
                </div>
                <button type="submit" disabled={loading || !url.trim()}
                  id="extract-btn" className="btn-primary px-6 py-3.5 text-base min-w-[160px]"
                  aria-label="Extract subtitles">
                  {loading ? (
                    <><div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full anim-spin" /> Extracting…</>
                  ) : (
                    <><Captions className="w-5 h-5" /> Extract</>
                  )}
                </button>
              </div>
            </form>

            <div id="url-hint" className="flex flex-wrap justify-center gap-x-5 gap-y-1.5 mt-4 text-xs font-semibold"
              style={{ color: 'var(--text-muted)' }}>
              {Object.entries(PLATFORMS).map(([name, cfg]) => (
                <span key={name} className="flex items-center gap-1.5">
                  <span style={{ color: cfg.color }}>{cfg.icon}</span> {name}
                </span>
              ))}
              <kbd className="px-1.5 py-0.5 rounded border text-[10px] font-mono hide-sm"
                style={{ borderColor: 'var(--border)', background: 'rgba(255,255,255,0.04)', color: 'var(--text-subtle)' }}>
                ⌘K
              </kbd>
            </div>

            {!data && !loading && !error && (
              <RecentSearches searches={recent} onSelect={handleSelectRecent} onClear={() => {
                localStorage.removeItem('subfetch_v2_recent'); setRecent([]);
              }} />
            )}
          </div>

          {/* Loading */}
          {loading && (
            <div className="max-w-3xl mx-auto mt-8 space-y-3 anim-fade-in" aria-busy="true" aria-label="Loading subtitles">
              <div className="card p-5 flex gap-4 items-center">
                <div className="skel anim-shimmer w-28 h-16 rounded-xl" />
                <div className="flex-1 space-y-2">
                  <div className="skel anim-shimmer h-3 w-20 rounded" />
                  <div className="skel anim-shimmer h-5 w-48 rounded" />
                  <div className="skel anim-shimmer h-3 w-28 rounded" />
                </div>
              </div>
              {[0,1,2].map(i => <SkeletonCard key={i} />)}
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            <div role="alert" className="max-w-3xl mx-auto mt-8 card p-5 flex items-start gap-4 anim-slide-up"
              style={{ opacity: 0, borderColor: 'rgba(248,113,113,0.2)' }}>
              <div className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                style={{ background: 'rgba(248,113,113,0.1)' }}>
                <AlertCircle className="w-5 h-5" style={{ color: 'var(--error)' }} />
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-bold text-sm mb-0.5" style={{ color: '#fca5a5' }}>Extraction failed</p>
                <p className="text-sm" style={{ color: 'rgba(252,165,165,0.7)' }}>{error}</p>
              </div>
              <button onClick={handleReset} className="pill shrink-0" aria-label="Try again">
                <RefreshCw className="w-3 h-3 inline mr-1" /> Retry
              </button>
            </div>
          )}

          {/* Results */}
          {data && !loading && (
            <div className="max-w-3xl mx-auto mt-8 space-y-4" aria-live="polite">
              <div className="card p-5 flex flex-col sm:flex-row gap-4 items-start sm:items-center anim-slide-up" style={{ opacity: 0 }}>
                {data.thumbnail && (
                  <div className="thumb-wrap w-28 h-16 shrink-0">
                    <img src={data.thumbnail} alt={`Thumbnail for ${data.title}`}
                      className="w-full h-full object-cover" loading="lazy" decoding="async"
                      onError={e => (e.currentTarget.parentElement!.style.display = 'none')} />
                    <div className="thumb-overlay" aria-hidden="true">
                      <Play className="w-5 h-5 text-white fill-white" />
                    </div>
                  </div>
                )}
                <div className="flex-1 min-w-0">
                  {(() => {
                    const p = PLATFORMS[data.platform];
                    return (
                      <span className={`badge ${p?.badge ?? 'badge-purple'} mb-1.5 inline-flex text-[10px]`}>
                        {p?.icon} {data.platform}
                      </span>
                    );
                  })()}
                  <h2 className="font-bold text-white text-base leading-snug line-clamp-2 mb-1">{data.title}</h2>
                  <p className="text-xs flex items-center gap-1" style={{ color: 'var(--text-muted)' }}>
                    <CheckCircle2 className="w-3 h-3" style={{ color: 'var(--success)' }} />
                    {data.subtitles.length} subtitle track{data.subtitles.length !== 1 ? 's' : ''} found
                  </p>
                </div>
                <button onClick={handleReset} className="pill shrink-0" aria-label="New search">New Search</button>
              </div>
              <div className="flex flex-wrap gap-x-5 gap-y-1.5 px-1 text-xs" style={{ color: 'var(--text-muted)' }}>
                {(Object.entries(FORMATS) as [DownloadFormat, (typeof FORMATS)[DownloadFormat]][]).map(([f, info]) => (
                  <span key={f}><strong className="text-white">{info.label}</strong> — {info.title}</span>
                ))}
              </div>
              <div className="space-y-3">
                {data.subtitles.map((sub, i) => (
                  <SubtitleCard key={`${sub.languageCode}-${i}`} sub={sub} title={data.title} index={i} />
                ))}
              </div>
            </div>
          )}
        </section>

        {/* ── Sections (home only) ─────────────────────────────── */}
        {showSections && (
          <>
            {/* How it Works */}
            <section id="how-it-works" aria-labelledby="hiw-heading" style={{ maxWidth: '80rem', margin: '0 auto', padding: '5rem 1.5rem' }}>
              <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
                <p className="eyebrow" style={{ marginBottom: '0.75rem' }}>Simple Process</p>
                <h2 id="hiw-heading" style={{ fontFamily: 'var(--font-head)', fontSize: 'clamp(1.75rem, 4vw, 2.25rem)', fontWeight: 900, color: 'white', letterSpacing: '-0.02em' }}>How to Download Subtitles</h2>
                <p style={{ marginTop: '0.75rem', maxWidth: '28rem', margin: '0.75rem auto 0', fontSize: '0.875rem', color: 'var(--text-muted)' }}>Three steps. No installation, no account.</p>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '1rem' }}>
                <StepCard n="1" title="Copy the URL" desc="Find your video on YouTube, Vimeo, or Dailymotion and copy the link from your browser." delay={0} />
                <StepCard n="2" title="Paste & Extract" desc="Paste the URL into the search box and click Extract. We detect the platform and fetch all available tracks." delay={100} />
                <StepCard n="3" title="Pick Format & Download" desc="Choose your language and format — SRT for editors, VTT for web players, TXT for AI tools — and download instantly." delay={200} />
              </div>
            </section>

            {/* Features */}
            <section id="features" aria-labelledby="features-heading" style={{ maxWidth: '80rem', margin: '0 auto', padding: '5rem 1.5rem' }}>
              <div style={{ textAlign: 'center', marginBottom: '3rem' }}>
                <p className="eyebrow" style={{ marginBottom: '0.75rem' }}>Why SubFetch</p>
                <h2 id="features-heading" style={{ fontFamily: 'var(--font-head)', fontSize: 'clamp(1.75rem, 4vw, 2.25rem)', fontWeight: 900, color: 'white', letterSpacing: '-0.02em' }}>Built for Speed &amp; Simplicity</h2>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1rem' }}>
                {[
                  { icon: <Zap className="w-5 h-5" />, title: 'Lightning Fast', desc: "Runs on Cloudflare's global edge network — subtitle extraction in under a second from anywhere.", delay: 0 },
                  { icon: <Shield className="w-5 h-5" />, title: 'Privacy First', desc: 'Stateless. We never store your URLs or subtitle data. Every request is independent.', delay: 80 },
                  { icon: <Globe2 className="w-5 h-5" />, title: 'Multi-language', desc: 'All subtitle tracks are listed — manual captions, auto-generated ASR, and community translations.', delay: 160 },
                  { icon: <FileText className="w-5 h-5" />, title: 'Three Formats', desc: 'Server-side conversion to SRT, VTT, or TXT with correct timestamps and encoding (UTF-8).', delay: 240 },
                  { icon: <CheckCircle2 className="w-5 h-5" />, title: 'No Registration', desc: 'Completely free. No email, no limits, no watermarks. Paste and go.', delay: 320 },
                  { icon: <Sparkles className="w-5 h-5" />, title: 'Auto-generated Captions', desc: "YouTube's speech-recognition captions are clearly labeled and fully supported.", delay: 400 },
                ].map((f, i) => <FeatureCard key={i} icon={f.icon} title={f.title} desc={f.desc} delay={f.delay} />)}
              </div>
            </section>

            {/* FAQ */}
            <section id="faq" aria-labelledby="faq-heading" style={{ maxWidth: '48rem', margin: '0 auto', padding: '5rem 1.5rem' }}>
              <div className="text-center mb-12">
                <p className="eyebrow mb-3">Got Questions?</p>
                <h2 id="faq-heading" className="text-3xl sm:text-4xl font-black text-white tracking-tight"
                  style={{ fontFamily: 'var(--font-head)' }}>Frequently Asked Questions</h2>
              </div>
              <div className="space-y-3" role="list">
                {FAQS.map((item, i) => <FAQItem key={i} q={item.q} a={item.a} index={i} />)}
              </div>
            </section>

            {/* CTA */}
            <section style={{ maxWidth: '72rem', margin: '0 auto', padding: '0 1.5rem 6rem' }} aria-labelledby="cta-heading">
              <div className="card p-10 sm:p-14 text-center relative overflow-hidden">
                <div aria-hidden="true" className="absolute inset-0 pointer-events-none"
                  style={{ background: 'linear-gradient(135deg, rgba(108,99,255,0.07) 0%, rgba(168,85,247,0.04) 100%)' }} />
                <div className="relative z-10">
                  <h2 id="cta-heading" className="text-2xl sm:text-3xl font-black text-white mb-3"
                    style={{ fontFamily: 'var(--font-head)' }}>Ready to Download Subtitles?</h2>
                  <p className="text-sm mb-7 max-w-sm mx-auto" style={{ color: 'var(--text-muted)' }}>
                    No sign-up. No installation. Paste a URL and download in seconds.
                  </p>
                  <button
                    onClick={() => { scrollTo({ top: 0, behavior: 'smooth' }); setTimeout(() => inputRef.current?.focus(), 700); }}
                    className="btn-primary px-8 py-3.5 text-base" aria-label="Get started">
                    <Download className="w-5 h-5" /> Get Started — It's Free
                  </button>
                </div>
              </div>
            </section>
          </>
        )}
      </main>
    </Layout>
  );
}
