export interface Subtitle {
  language: string;
  languageCode: string;
  url: string;
  format: string;
  isAutoGenerated?: boolean;
  name?: string;
}

export interface ExtractorResult {
  platform: string;
  title: string;
  thumbnail?: string;
  subtitles: Subtitle[];
}

export interface Extractor {
  id: string;
  canHandle(url: string): boolean;
  extract(url: string): Promise<ExtractorResult>;
}
