import type { Extractor, ExtractorResult } from './base';

export const dailymotionExtractor: Extractor = {
  id: 'dailymotion',
  canHandle: (url) => /dailymotion\.com|dai\.ly/.test(url),

  extract: async (url): Promise<ExtractorResult> => {
    const idMatch = url.match(/(?:dailymotion\.com\/video\/|dai\.ly\/)([a-z0-9]+)/i);
    if (!idMatch?.[1]) {
      throw new Error('Invalid Dailymotion URL — could not find a video ID.');
    }
    const videoId = idMatch[1];

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15_000);

    try {
      // Dailymotion's internal player API is much more reliable than the public API for subtitles
      const apiUrl = `https://www.dailymotion.com/player/metadata/video/${videoId}`;
      const response = await fetch(apiUrl, {
        headers: { 
          'Accept': 'application/json',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
        },
        signal: controller.signal,
      });

      if (response.status === 404) throw new Error('Dailymotion video not found.');
      if (!response.ok) throw new Error(`Dailymotion API returned HTTP ${response.status}.`);

      const data = await response.json();
      const subtitleData = data?.subtitles?.data ?? [];

      if (subtitleData.length === 0) {
        throw new Error('No subtitles found for this Dailymotion video.');
      }

      const subtitles = subtitleData
        .map((track: any) => ({
          language: track.language ?? track.name ?? 'Unknown',
          languageCode: track.language_code ?? track.language ?? 'unknown',
          url: track.urls?.[0] ?? '',
          format: 'srt', // DM usually provides SRT/VTT
          isAutoGenerated: false,
          name: track.language ?? track.name,
        }))
        .filter((s: any) => s.url);

      if (subtitles.length === 0) {
        throw new Error('Subtitles exist but no valid download URLs were found.');
      }

      const thumbnail = data.posters?.['720'] ?? data.posters?.['480'] ?? undefined;

      return {
        platform: 'Dailymotion',
        title: data.title ?? 'Dailymotion Video',
        thumbnail,
        subtitles,
      };
    } finally {
      clearTimeout(timeout);
    }
  },
};
