import type { Extractor, ExtractorResult } from './base';

export const dailymotionExtractor: Extractor = {
  id: 'dailymotion',
  canHandle: (url) => /dailymotion\.com|dai\.ly/.test(url),

  extract: async (url): Promise<ExtractorResult> => {
    const idMatch = url.match(/(?:dailymotion\.com\/video\/|dai\.ly\/)([a-z0-9]+)/i);
    if (!idMatch?.[1]) {
      throw new Error('Invalid Dailymotion URL — could not find a video ID.');
    }
    const videoId = idMatch[1];

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15_000);

    let data: any;
    try {
      const apiUrl = `https://api.dailymotion.com/video/${videoId}?fields=title,thumbnail_480_url,subtitles`;
      const response = await fetch(apiUrl, {
        headers: { 'Accept': 'application/json' },
        signal: controller.signal,
      });

      if (response.status === 404) throw new Error('Dailymotion video not found.');
      if (!response.ok) throw new Error(`Dailymotion API returned HTTP ${response.status}.`);

      data = await response.json();
    } finally {
      clearTimeout(timeout);
    }

    const subtitleList: any[] = data?.subtitles?.list ?? [];

    if (subtitleList.length === 0) {
      throw new Error('No subtitles found for this Dailymotion video.');
    }

    const subtitles = subtitleList
      .map((track: any) => ({
        language: track.language_label ?? track.language ?? 'Unknown',
        languageCode: track.language ?? 'unknown',
        url: track.urls?.[0] ?? '',
        format: 'srt',
        isAutoGenerated: false,
        name: track.language_label ?? track.language,
      }))
      .filter((s) => s.url);

    return {
      platform: 'Dailymotion',
      title: data.title ?? 'Dailymotion Video',
      thumbnail: data.thumbnail_480_url ?? undefined,
      subtitles,
    };
  },
};
