import type { Extractor, ExtractorResult } from './base';

export const vimeoExtractor: Extractor = {
  id: 'vimeo',
  canHandle: (url) => /vimeo\.com/.test(url),

  extract: async (url): Promise<ExtractorResult> => {
    // Support formats: vimeo.com/123456, vimeo.com/video/123456, player.vimeo.com/video/123456
    const idMatch = url.match(/vimeo\.com\/(?:video\/)?(\d+)/);
    if (!idMatch?.[1]) {
      throw new Error('Invalid Vimeo URL — could not find a numeric video ID.');
    }
    const videoId = idMatch[1];

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 15_000);

    let data: any;
    try {
      const response = await fetch(`https://player.vimeo.com/video/${videoId}/config`, {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
          'Referer': `https://vimeo.com/${videoId}`,
          'Accept': 'application/json',
          'Accept-Language': 'en-US,en;q=0.9',
        },
        signal: controller.signal,
      });

      if (response.status === 403) {
        throw new Error('This Vimeo video is private or domain-restricted. Cannot extract subtitles.');
      }
      if (response.status === 404) {
        throw new Error('Vimeo video not found. Check the URL.');
      }
      if (!response.ok) {
        throw new Error(`Vimeo returned HTTP ${response.status}.`);
      }

      data = await response.json();
    } finally {
      clearTimeout(timeout);
    }

    const tracks: any[] = data?.request?.text_tracks ?? [];

    if (tracks.length === 0) {
      throw new Error('No subtitles found for this Vimeo video. The creator may not have added captions.');
    }

    const subtitles = tracks
      .filter((track: any) => track.url) // only tracks with a valid URL
      .map((track: any) => {
        // Vimeo track URLs can be relative (/texttrack/...) or absolute
        const rawUrl: string = track.url ?? '';
        const trackUrl = rawUrl.startsWith('http') ? rawUrl : `https://vimeo.com${rawUrl}`;
        return {
          language: track.label ?? track.lang ?? 'Unknown',
          languageCode: track.lang ?? 'unknown',
          url: trackUrl,
          format: 'vtt',
          isAutoGenerated: false,
          name: track.label ?? track.lang,
        };
      });

    if (subtitles.length === 0) {
      throw new Error('Subtitle tracks found but had no valid download URLs.');
    }

    // Extract best quality thumbnail
    const thumbs = data?.video?.thumbs ?? {};
    const thumbnail: string | undefined =
      thumbs['1280'] ?? thumbs['960'] ?? thumbs['640'] ?? thumbs['100'] ?? undefined;

    return {
      platform: 'Vimeo',
      title: data?.video?.title ?? 'Vimeo Video',
      thumbnail,
      subtitles,
    };
  },
};
